### ISSUE TITLE
Language files location

### ISSUE THREAD

**Issue by timrijkse** [Blocklevel/blue#37]
I see the language files are located in `/static`. Shouldn't they be in `/asset` to avoid caching?

**Comment by MatteoGabriele** [comment]
I don't know what the actual webpack configuration does with assets and static folders.  Language files are based on the application setup,  so they can be everywhere in the actual structure.  
The plugin handles only runtime cache to avoid multiple http requests.

**Comment by jonaskuiler** [comment]
@timrijkse Everything inside the ``static`` folder will be moved to the ``dist/version`` folder, so they will not be cached when deploying a new release. 

This separation is probably also used to provide support for a CDN.
