### ISSUE TITLE
Check timestamp/version for backend blade file

### ISSUE THREAD

**Issue by timrijkse** [Blocklevel/blue#5]
We have to test a build with backend to see if all assets load correctly.

**Comment by jonaskuiler** [comment]
I've tested this and it's working correctly, still need to check this with @floristenhove

**Comment by timrijkse** [comment]
Did you check it? :)

**Comment by floristenhove** [comment]
@jonaskuiler let me know what to check.

**Comment by jonaskuiler** [comment]
I think there's no need to check it anymore, I've already tested this in a client project :).
