### ISSUE TITLE
browser detection

### ISSUE THREAD

**Issue by MatteoGabriele** [Blocklevel/blue#52]
implement [detect-browser](https://www.npmjs.com/package/detect-browser) package for browser detection

**Comment by MatteoGabriele** [comment]
probably better to try [sniffr](https://www.npmjs.com/package/sniffr) which is handling browser and device detection together

**Comment by jonaskuiler** [comment]
I'm creating a Vue plugin that exposes an API like this so it integrates well with the way we work. I don't want to bloat this boilerplate with a lot of dependencies like this. 

Vue itself was designed to be a progressive framework so we should really invest in creating a more packaged structure and thus isolate functionality like this in a Vue plugin.

This boilerplate should contain a minimal setup and folder structure which enables developers to use the features of Vue.
